name: Clean up old releases

on:
  workflow_dispatch:
  schedule:
    # At minute 0 past hour 0. (see https://crontab.guru)
    - cron: '00 00 * * *'

jobs:

  delete_releases:

    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v6.0.0
        with:
          python-version: "3.10"

      - name: Delete from here
        shell: bash
        run: |
          
          pip install PyGithub
          GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} python scripts/clean_gh_releases.py

  call-deploy-pip-page:

    if: (github.event_name == 'push' && github.ref_name == 'main') || github.event_name == 'workflow_dispatch'

    needs: [delete_releases]

    permissions:
      contents: read
      id-token: write
      pages: write

    uses: ./.github/workflows/deploy_pip_page.yml
    secrets: inherit # pass all secrets
